security:
    encoders:
        TeAyudo\TeAyudoBundle\Entity\User:
            algorithm: bcrypt
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity:
                class: TeAyudo\TeAyudoBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            #logout:
             #   path:   _demo_logout
              #  target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
              login_path: /home
              check_path: login_check
            logout:
                path:   logout
                target: /home
              
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }