_welcome:
    path: /home
    defaults: { _controller: TeAyudoBundle:Index:index }
    
_mainView:
    path:     /main
    defaults: { _controller: TeAyudoBundle:MainView:show }
    
_creation:
    path:     /create
    defaults: { _controller: TeAyudoBundle:Create:show }
    
_publication:
    path:     /publication/{cycleId}
    defaults: {_controller: TeAyudoBundle:Publication:show}
    
_allPublications:
    path:     /all
    defaults: {_controller: TeAyudoBundle:AllPublications:show}
    
_admin:
    path:     /admin
    defaults: { _controller: TeAyudoBundle:Admin:index }
    
_cycles:
    path:     /myCycles
    defaults: { _controller: TeAyudoBundle:MyCycles:show }
    
_deleteCycle:
    path:     /myCycles/delete/{id}
    defaults: { _controller: TeAyudoBundle:MyCycles:deleteCycle }
    
_userAccount:
    path:     /myAccount
    defaults: { _controller: TeAyudoBundle:MyAccount:show }
    
_viewPublication:
    path:     /publication
    defaults: { _controller: TeAyudoBundle:Publication:show }
    
login:
    path: /login
    defaults: { _controller: TeAyudoBundle:Index:index }
login_check:
    path: /login_check
logout:
    path: /logout
    defaults: { _controller: TeAyudoBundle:Index:index }