parameters:
#    te_ayudo.example.class: TeAyudo\TeAyudoBundle\Example

services:
#    te_ayudo.example:
#        class: %te_ayudo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
