TeAyudo\TeAyudoBundle\Entity\User:
properties:
name:
- NotBlank: ~
password:
- NotBlank: ~

Acme\DemoBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 6000000